fragment TaskFields on Task { 
    id
    version
    title
    description
    status
}

mutation createTask {
  createTask(input: {title: "Task1", description: "test", status: "CREATED"}) {
     ...TaskFields
  }
}

query findAllTasks {
  findAllTasks{
    ...TaskFields
  }
}

mutation updateTask {
  updateTask(input: {id: "1", title: "Task2", version: 1}) {
    ...TaskFields
  }
}

